const STORAGE_KEY='joseluis-portal-v3';
const LEGACY_KEY='joseluis-portal-v1';

const RADAR=[
 {id:'gmf-brussels-2026',title:'GMF — Program & Research Trainee',institution:'German Marshall Fund',country:'Bélgica',city:'Bruselas',funding:'€1.000–1.200 netos/mes',deadline:'',status:'preparing',priority:'Alta',sourceUrl:'https://recruiting.paylocity.com/Recruiting/Jobs/Details/4320819',why:'Investigación aplicada, policy support, sociedad civil y coordinación.',notes:'Sept 2026–ene 2027. Apply activo; visa/patrocinio no confirmado.',requirements:[r('cv','CV actualizado','document','CV'),r('degree','Título','document','Estudios'),r('motivation','Carta de motivación','easy'),r('english','Inglés fluido','action'),r('visa','Situación migratoria Bélgica','action')]},
 {id:'blue-book-2027',title:'Blue Book Traineeship — Mar 2027',institution:'Comisión Europea',country:'Bélgica / UE',city:'Bruselas',funding:'≈ €1.572/mes en Bélgica',deadline:'2026-09-04',status:'preparing',priority:'Muy alta',sourceUrl:'https://traineeships.ec.europa.eu/about/calendar-sessions_en',why:'Políticas públicas, asuntos sociales, empleo, cohesión, evaluación y programas UE.',notes:'Cierre 4 sep 2026 10:00 Bruselas. No UE: selección excepcional y limitada.',requirements:[r('cv','CV','document','CV'),r('degree','Título universitario','document','Estudios'),r('transcript','Notas / transcript','document','Estudios'),r('english','C1 inglés/francés/alemán','action'),r('application','Formulario Blue Book','easy')]},
 {id:'cor-cicero-2027',title:'Cicero Traineeship — Spring 2027',institution:'European Committee of the Regions',country:'Bélgica',city:'Bruselas',funding:'≈ €1.400/mes',deadline:'2026-10-01',status:'preparing',priority:'Alta',sourceUrl:'https://www.cor.europa.eu/en/about/work-us/traineeships',why:'Cohesión territorial, política social, empleo, educación y gobiernos locales.',notes:'Sesión 16 feb–15 jul 2027. Terceros países: selección excepcional.',requirements:[r('cv','CV','document','CV'),r('degree','Título','document','Estudios'),r('motivation','Motivación','easy'),r('english','Inglés o francés','action')]},
 {id:'schuman-2027',title:'Schuman Traineeship — Mar 2027',institution:'Parlamento Europeo',country:'UE',city:'Bruselas / Luxemburgo / Estrasburgo',funding:'Remunerada',deadline:'2026-10-31',status:'considering',priority:'Alta',sourceUrl:'https://www.europarl.europa.eu/at-your-service/en/work-with-us/traineeships',why:'Políticas sociales, empleo, educación, cohesión, investigación y análisis.',notes:'Ventana 1–31 oct 2026. Hasta 3 candidaturas. No UE: plazas muy limitadas.',requirements:[r('cv','CV','document','CV'),r('degree','Título','document','Estudios'),r('motivation','Motivación','easy'),r('english','Muy buen inglés/francés/alemán','action')]},
 {id:'eit-2027',title:'EIT Traineeship Programme 2027',institution:'European Institute of Innovation and Technology',country:'Hungría / Bélgica',city:'Budapest / Bruselas',funding:'≈ €1.500 netos/mes',deadline:'2026-09-15',status:'preparing',priority:'Muy alta',sourceUrl:'https://www.eit.europa.eu/work-with-us/careers/vacancies/open',why:'Monitoring, reporting, evaluación, educación e innovación.',notes:'Cierre 15 sep 2026 13:00. Se pueden elegir 2 áreas. No UE: número limitado.',requirements:[r('cv','EU CV Online','easy'),r('degree','Título','document','Estudios'),r('english','Inglés B2+','action'),r('preferences','Elegir 2 áreas','easy')]},
 {id:'unesco-internship-2026',title:'UNESCO Internship — All Sectors',institution:'UNESCO',country:'Francia / internacional',city:'París',funding:'No remunerada',deadline:'2026-12-31',status:'considering',priority:'Media',sourceUrl:'https://careers.unesco.org/job/Multiple-INTERNSHIP-All-Sectors-Bureaus/1331682557/',why:'Investigación, informes, datos, talleres, educación y ciencias sociales.',notes:'1–6 meses. Graduación dentro de últimos 12 meses. Visa/viaje/seguro a cargo del candidato.',requirements:[r('cv','CV','document','CV'),r('degree','Título','document','Estudios'),r('english','Excelente inglés o francés','action'),r('application','Perfil UNESCO','easy')]},
 {id:'oecd-yap-2027',title:'OECD Young Associates Programme 2027',institution:'OECD',country:'Francia',city:'París',funding:'≈ €3.886/mes + beneficios',deadline:'',status:'considering',priority:'Muy alta',sourceUrl:'https://www.oecd.org/content/dam/oecd/en/about/careers/young-associates/YAP-Brochure.pdf',why:'Policy, investigación y análisis en empleo, educación, regiones, estadísticas y desarrollo.',notes:'Preparar para noviembre 2026. Ayuda con visa/permisos para seleccionados no UE.',requirements:[r('cv','CV','document','CV'),r('degree','Bachelor','document','Estudios'),r('grades','GPA / notas','document','Estudios'),r('english','Inglés o francés fluido','action'),r('eligibility','Verificar regla Bachelor ≤20 meses y sin máster','action')]},
 {id:'mundus-mapp-2027',title:'Mundus MAPP 2027–2029',institution:'Erasmus Mundus / CEU / IBEI / ISS / York',country:'Europa',city:'Varios',funding:'Beca: matrícula + €1.400/mes x24',deadline:'2026-12-01',status:'preparing',priority:'Muy alta',sourceUrl:'https://www.mundusmapp.org/admissions-calendar/',why:'Sociología → policy analysis y evidence-based public policy.',notes:'Cierre beca 1 dic 2026 23:59 CET. Inglés certificado debe estar listo al postular.',requirements:[r('cv','CV','document','CV'),r('degree','Bachelor','document','Estudios'),r('transcript','Notas / transcript','document','Estudios'),r('motivation','Motivación','easy'),r('english','IELTS 7 / TOEFL 95 / Duolingo 130 u opción aceptada','action')]},
 {id:'sciencespo-luksic-2027',title:'Sciences Po + Luksic Scholarship',institution:'Sciences Po',country:'Francia',city:'París',funding:'100% matrícula + manutención',deadline:'',status:'preparing',priority:'Muy alta',sourceUrl:'https://www.sciencespo.fr/students/en/fees-funding/bursaries-financial-aid/luksic-scholarship/',why:'Beca específica para ciudadanos chilenos en Public Affairs / PSIA.',notes:'Admisiones 2027 abren fin sep 2026; beca 2027–28 prevista sep/oct–ene. Fecha exacta por confirmar.',requirements:[r('cv','CV','document','CV'),r('degree','Título','document','Estudios'),r('transcript','Notas','document','Estudios'),r('motivation','Motivación / servicio público','easy'),r('english','Idioma según máster','action'),r('eligibility','Confirmar residencia Chile y no doble nacionalidad UE','action')]},
 {id:'france-working-holiday',title:'France Working Holiday — Chile',institution:'France-Visas / Campus France',country:'Francia',city:'Francia',funding:'Visa de trabajo hasta 12 meses',deadline:'',status:'considering',priority:'Plan B',sourceUrl:'https://www.campusfrance.org/fr/le-visa-vacances-travail',why:'Puede eliminar la barrera de permiso de trabajo para roles junior en Francia.',notes:'Condicionado a edad 18–30 y no haber usado antes el programa. No sustituye una candidatura laboral.',requirements:[r('passport','Pasaporte','document','Otros'),r('age','Verificar edad elegible','action'),r('history','Confirmar no uso previo','action'),r('funds','Recursos iniciales / retorno','action')]}
];

function r(id,label,type,category=''){return {id,label,type,category,state:type==='easy'?'easy':'action'}}
const seed={profile:{name:'José Luis',country:'Chile',field:'Sociología'},documents:[
 {id:'known-cv',name:'CV',category:'CV',status:'to-locate',version:1},
 {id:'known-degree',name:'Título universitario',category:'Estudios',status:'to-locate',version:1},
 {id:'known-transcript',name:'Certificado de notas / transcript',category:'Estudios',status:'to-locate',version:1}
],opportunities:RADAR,history:[]};

function clone(x){return JSON.parse(JSON.stringify(x))}
function migrate(){
 let s=null;try{s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{}
 if(!s){try{s=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null')}catch{}}
 if(!s)s=clone(seed);
 s.profile={...seed.profile,...(s.profile||{})};
 s.documents=Array.isArray(s.documents)?s.documents:clone(seed.documents);
 // Older demo metadata must not imply that an actual file is stored.
 s.documents=s.documents.map(d=>({...d,status:d.fileStored?'ready':(d.status==='ready'?'to-locate':(d.status||'to-locate'))}));
 const manual=(s.opportunities||[]).filter(o=>!/^opp-(daad|barcelona|erasmus|fulbright)$/.test(o.id||''));
 const existing=new Map(manual.map(o=>[o.id,o]));
 s.opportunities=RADAR.map(o=>({...clone(o),...(existing.get(o.id)||{})})).concat(manual.filter(o=>!RADAR.some(r=>r.id===o.id)));
 localStorage.setItem(STORAGE_KEY,JSON.stringify(s));return s;
}
let state=migrate();let filter='all';let docFilter='all';
const $=q=>document.querySelector(q);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses={new:'Nueva',considering:'Mirando',preparing:'Preparando',ready:'Lista',submitted:'Enviada',closed:'Cerrada'};
const nav=[['home','⌂','Inicio'],['opportunities','◉','Oportunidades'],['documents','▢','Documentos'],['profile','♙','Perfil']];
function save(msg=''){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(msg)toast(msg)}
function route(){const [page='home',id]=location.hash.replace(/^#/,'').split('/');return {page:page||'home',id}}
function renderNav(){const p=route().page;const h=nav.map(([id,ic,l])=>`<a class="nav-link ${(p===id||(p==='opportunity'&&id==='opportunities'))?'active':''}" href="#${id}"><span class="nav-icon">${ic}</span><span>${l}</span></a>`).join('');$('#desktop-nav').innerHTML=h;$('#mobile-nav').innerHTML=h}
function render(){renderNav();const x=route();$('#main').innerHTML=x.page==='opportunities'?oppsPage():x.page==='opportunity'?oppPage(x.id):x.page==='documents'?docsPage():x.page==='profile'?profilePage():homePage();bind()}
function days(d){return d?Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000):null}
function fmt(d){if(!d)return '';return new Intl.DateTimeFormat('es',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'))}
function readyDoc(cat){return state.documents.some(d=>d.category===cat&&d.status==='ready')}
function sync(o){(o.requirements||[]).forEach(q=>{if(q.type==='document')q.state=readyDoc(q.category)?'ready':'action'})}

function homePage(){const active=state.opportunities.filter(o=>o.status!=='closed');const newN=active.filter(o=>o.status==='new').length;const dated=active.filter(o=>o.deadline&&days(o.deadline)>=0).sort((a,b)=>a.deadline.localeCompare(b.deadline));const next=dated[0],d=next?days(next.deadline):null;const urgent=d!==null&&d<=5;return `<section class="page app-home"><div class="page-head compact"><h1>${esc(state.profile.name||'José Luis')}</h1></div><div class="app-state ${urgent?'urgent':''}"><span>${urgent?'!':'✓'}</span><strong>${urgent?`${d} días`:'Todo al día'}</strong></div><div class="app-cards"><a href="#opportunities" class="app-card"><b>${active.length}</b><span>Procesos</span></a><a href="#documents" class="app-card"><b>${state.documents.length}</b><span>Documentos</span></a><a href="#opportunities" class="app-card"><b>${newN}</b><span>Nuevas</span></a></div>${next?`<div class="next-line">${esc(next.title)} · ${fmt(next.deadline)}</div>`:''}</section>`}
function oppsPage(){const list=state.opportunities.filter(o=>filter==='all'||o.status===filter).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));return `<section class="page"><div class="page-head compact"><h1>Oportunidades</h1><button class="circle-action" data-action="add-opp">+</button></div><div class="filters compact-filters">${[['all','Todas'],['preparing','Preparando'],['considering','Mirando'],['submitted','Enviadas']].map(([k,l])=>`<button class="pill ${filter===k?'active':''}" data-filter="${k}">${l}</button>`).join('')}</div><div class="app-list">${list.map(o=>`<a class="app-row" href="#opportunity/${o.id}"><div><strong>${esc(o.title)}</strong><span>${esc(o.country)}${o.deadline?` · ${fmt(o.deadline)}`:''}</span></div><div class="row-side"><span class="mini-priority">${esc(o.priority||statuses[o.status]||'')}</span><b>›</b></div></a>`).join('')}</div></section>`}
function oppPage(id){const o=state.opportunities.find(x=>x.id===id);if(!o)return `<section class="page"><h1>No encontrada</h1></section>`;sync(o);const req=o.requirements||[],ready=req.filter(x=>x.state==='ready'),easy=req.filter(x=>x.state==='easy'),todo=req.filter(x=>x.state==='action');const next=todo[0]||easy[0];return `<section class="page"><a class="back-link" href="#opportunities">‹ Oportunidades</a><div class="opp-hero"><span class="mini-priority">${esc(o.priority||'')}</span><h1>${esc(o.title)}</h1><div class="opp-place">${esc(o.country)}${o.city?` · ${esc(o.city)}`:''}</div><div class="fact-strip"><span><b>${esc(o.funding||'—')}</b><small>Financiación</small></span><span><b>${o.deadline?fmt(o.deadline):'—'}</b><small>Plazo</small></span></div><div class="state-strip"><span class="ok"><b>${ready.length}</b><small>Listo</small></span><span class="easy"><b>${easy.length}</b><small>Fácil</small></span><span class="todo"><b>${todo.length}</b><small>Por resolver</small></span></div>${next?`<button class="next-card" data-action="next-req" data-id="${o.id}" data-req="${next.id}"><span>Siguiente</span><strong>${esc(next.label)}</strong><b>›</b></button>`:''}<details class="details-panel"><summary>Detalles</summary><div class="detail-body"><div class="short-note">${esc(o.why||'')}</div><div class="req-list">${req.map(q=>`<button class="req-row" data-action="req" data-id="${o.id}" data-req="${q.id}"><span class="dot ${q.state}">${q.state==='ready'?'✓':q.state==='easy'?'○':'!'}</span><span>${esc(q.label)}</span><b>›</b></button>`).join('')}</div><div class="detail-actions"><select data-action="status" data-id="${o.id}">${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${o.status===k?'selected':''}>${v}</option>`).join('')}</select>${o.sourceUrl?`<a class="button soft" href="${esc(o.sourceUrl)}" target="_blank" rel="noopener">Oficial ↗</a>`:''}</div><div class="small-note">${esc(o.notes||'')}</div></div></details></div></section>`}
function docsPage(){const cats=['all','CV','Estudios','Idiomas','Recomendaciones','Muestras','Otros'];const counts=Object.fromEntries(cats.slice(1).map(c=>[c,state.documents.filter(d=>d.category===c).length]));const docs=docFilter==='all'?state.documents:state.documents.filter(d=>d.category===docFilter);return `<section class="page"><div class="page-head compact"><h1>Documentos</h1><button class="circle-action" data-action="upload">+</button></div><div class="wallet-list">${cats.slice(1).map(c=>`<button class="wallet-row ${docFilter===c?'active':''}" data-docfilter="${c}"><span>${icon(c)}</span><strong>${c}</strong><b>${counts[c]||0}</b><i>›</i></button>`).join('')}</div>${docFilter!=='all'?`<div class="doc-items">${docs.map(d=>`<div class="doc-item"><div><strong>${esc(d.name)}</strong><span>${d.status==='ready'?'Guardado':'Por localizar'}</span></div><span class="mini-priority">v${d.version||1}</span></div>`).join('')||'<div class="empty">Sin archivos</div>'}</div>`:''}</section>`}
function icon(c){return {CV:'📄',Estudios:'🎓',Idiomas:'🌐',Recomendaciones:'👤',Muestras:'✎',Otros:'📁'}[c]||'📁'}
function profilePage(){const p=state.profile||{};return `<section class="page"><div class="page-head compact"><h1>Perfil</h1><button class="circle-action" data-action="edit-profile">✎</button></div><div class="profile-app"><div><span>Nombre</span><strong>${esc(p.name||'—')}</strong></div><div><span>País</span><strong>${esc(p.country||p.city||'—')}</strong></div><div><span>Área</span><strong>${esc(p.field||p.education||'—')}</strong></div></div></section>`}

function bind(){document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.querySelectorAll('[data-docfilter]').forEach(b=>b.onclick=()=>{docFilter=b.dataset.docfilter;render()});document.querySelectorAll('[data-action]').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound='1';const a=el.dataset.action;if(a==='status')el.onchange=()=>{const o=state.opportunities.find(x=>x.id===el.dataset.id);o.status=el.value;save();render()};else if(a==='add-opp')el.onclick=addOpp;else if(a==='upload')el.onclick=()=>$('#file-input').click();else if(a==='edit-profile')el.onclick=editProfile;else if(a==='req'||a==='next-req')el.onclick=()=>openReq(el.dataset.id,el.dataset.req)})}
function addOpp(){openModal(`<h2>Nueva oportunidad</h2><label>Título<input id="m-title" autofocus></label><label>Link<input id="m-url"></label><div class="modal-actions"><button class="button primary" id="m-save">Guardar</button></div>`);$('#m-save').onclick=()=>{const t=$('#m-title').value.trim();if(!t)return;state.opportunities.unshift({id:'manual-'+Date.now(),title:t,institution:'',country:'',funding:'',deadline:'',status:'new',priority:'',sourceUrl:$('#m-url').value.trim(),why:'',notes:'',requirements:[]});save('Guardado');closeModal();render()}}
function editProfile(){const p=state.profile;openModal(`<h2>Perfil</h2><label>Nombre<input id="p-name" value="${esc(p.name||'')}"></label><label>País<input id="p-country" value="${esc(p.country||'')}"></label><label>Área<input id="p-field" value="${esc(p.field||'')}"></label><div class="modal-actions"><button class="button primary" id="p-save">Guardar</button></div>`);$('#p-save').onclick=()=>{p.name=$('#p-name').value;p.country=$('#p-country').value;p.field=$('#p-field').value;save('Guardado');closeModal();render()}}
function openReq(id,rid){const o=state.opportunities.find(x=>x.id===id),q=(o.requirements||[]).find(x=>x.id===rid);if(!q)return;if(q.type==='document'){openModal(`<h2>${esc(q.label)}</h2><p>${readyDoc(q.category)?'Ya está guardado.':'Todavía no hay un archivo real guardado.'}</p><button class="button primary" id="u-doc">Subir</button>`);$('#u-doc').onclick=()=>$('#file-input').click();return}const special=q.id==='english'?'Revisa qué certificado o nivel acepta esta convocatoria.':q.id==='motivation'?'Podemos preparar un borrador usando el perfil y esta oportunidad.':'Completa este punto cuando tengas la información.';openModal(`<h2>${esc(q.label)}</h2><p>${special}</p><div class="modal-actions"><button class="button primary" id="mark-done">Marcar listo</button></div>`);$('#mark-done').onclick=()=>{q.state='ready';save('Listo');closeModal();render()}}
function openModal(html){$('#modal-content').innerHTML=`<div class="modal-card"><div class="modal-head"><span></span><button class="close" onclick="document.querySelector('#modal').close()">×</button></div><div class="form-grid">${html}</div></div>`;$('#modal').showModal()}
function closeModal(){$('#modal').close()}
function toast(t){let x=$('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=t;setTimeout(()=>x.remove(),1400)}
$('#file-input').addEventListener('change',e=>{[...e.target.files].forEach(f=>{const cat=guess(f.name);const dup=state.documents.some(d=>d.name===f.name&&d.size===f.size&&d.lastModified===f.lastModified);if(!dup)state.documents.push({id:'doc-'+Date.now()+Math.random(),name:f.name,category:cat,status:'ready',fileStored:false,size:f.size,lastModified:f.lastModified,version:1})});save('Documento registrado');e.target.value='';render()});
function guess(n){n=n.toLowerCase();if(n.includes('cv')||n.includes('curric'))return 'CV';if(n.includes('transcript')||n.includes('titulo')||n.includes('diplom')||n.includes('nota'))return 'Estudios';if(n.includes('ielts')||n.includes('toefl')||n.includes('english')||n.includes('idioma'))return 'Idiomas';if(n.includes('recommend')||n.includes('refer'))return 'Recomendaciones';return 'Otros'}
window.addEventListener('hashchange',render);render();
