const STORAGE_KEY='joseluis-portal-v1';

const seedState={
  profile:{name:'José Luis',email:'',phone:'',city:'Chile',education:'Sociología',experience:'',languages:'Español; Inglés por completar',skills:'Investigación social; análisis; redacción',references:''},
  documents:[
    {id:'d1',name:'CV_actual.pdf',category:'CV',version:1,status:'ready',size:0,lastModified:0,updated:'2026-08-31'},
    {id:'d2',name:'Título_profesional.pdf',category:'Académicos',version:1,status:'ready',size:0,lastModified:0,updated:'2026-08-31'},
    {id:'d3',name:'Transcript.pdf',category:'Académicos',version:1,status:'ready',size:0,lastModified:0,updated:'2026-08-31'}
  ],
  opportunities:[
    {id:'opp-daad',title:'DAAD — programa por revisar',institution:'DAAD',country:'Alemania',funding:'Por verificar',deadline:'',status:'new',source:'Radar inicial',sourceUrl:'https://www.daad.de/en/studying-in-germany/scholarships/',why:'Opción añadida desde el radar. Conviene revisar programas compatibles con sociología y orientación profesional.',notes:'Datos concretos del programa aún por verificar.',requirements:[
      {id:'cv',label:'CV actualizado',type:'document',category:'CV',state:'ready'},
      {id:'degree',label:'Título / diploma',type:'document',category:'Académicos',state:'ready'},
      {id:'motivation',label:'Carta de motivación',type:'easy',state:'easy'},
      {id:'english',label:'Requisito de idioma',type:'action',state:'action'}]},
    {id:'opp-barcelona',title:'Máster / oportunidad en Barcelona',institution:'Por definir',country:'España',funding:'Por verificar',deadline:'',status:'considering',source:'Radar inicial',sourceUrl:'',why:'Oportunidad mantenida en consideración mientras se comparan programa, salida profesional y financiación.',notes:'Completar institución y convocatoria exacta cuando quede confirmada.',requirements:[
      {id:'cv',label:'CV actualizado',type:'document',category:'CV',state:'ready'},
      {id:'degree',label:'Título / diploma',type:'document',category:'Académicos',state:'ready'},
      {id:'transcript',label:'Certificado de notas / transcript',type:'document',category:'Académicos',state:'ready'},
      {id:'motivation',label:'Carta de motivación',type:'easy',state:'easy'}]},
    {id:'opp-erasmus',title:'Erasmus+ — opción por revisar',institution:'Unión Europea',country:'Europa',funding:'Según programa',deadline:'',status:'new',source:'Radar inicial',sourceUrl:'https://erasmus-plus.ec.europa.eu/',why:'Se conserva en el radar para comprobar programas concretos que encajen con su perfil y objetivos.',notes:'No tratar como candidatura hasta identificar convocatoria concreta.',requirements:[{id:'cv',label:'CV actualizado',type:'document',category:'CV',state:'ready'}]},
    {id:'opp-fulbright',title:'Fulbright — opción por revisar',institution:'Fulbright',country:'Internacional',funding:'Según convocatoria',deadline:'',status:'new',source:'Radar inicial',sourceUrl:'https://foreign.fulbrightonline.org/',why:'Se mantiene como referencia internacional hasta encontrar una convocatoria realmente pertinente.',notes:'Verificar elegibilidad chilena y modalidad concreta.',requirements:[{id:'cv',label:'CV actualizado',type:'document',category:'CV',state:'ready'},{id:'english',label:'Requisito de inglés',type:'action',state:'action'}]}
  ],
  history:[{at:new Date().toISOString(),text:'Portal inicializado con oportunidades del radar'}]
};

let state=loadState();
let activeFilter='all';

const navItems=[['home','⌂','Inicio'],['opportunities','◉','Oportunidades'],['documents','▢','Documentos'],['profile','♙','Perfil']];

function clone(v){return JSON.parse(JSON.stringify(v))}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||clone(seedState)}catch{return clone(seedState)}}
function saveState(msg){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(msg){state.history.unshift({at:new Date().toISOString(),text:msg});localStorage.setItem(STORAGE_KEY,JSON.stringify(state));toast('Guardado automáticamente')}}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){if(!v)return 'Sin fecha aún';const d=new Date(v+'T12:00:00');return new Intl.DateTimeFormat('es',{day:'numeric',month:'short',year:'numeric'}).format(d)}
function daysTo(v){if(!v)return null;return Math.ceil((new Date(v+'T23:59:59')-new Date())/86400000)}
function statusLabel(s){return {new:'Nueva',considering:'En consideración',preparing:'En preparación',ready:'Lista',submitted:'Enviada',closed:'Cerrada'}[s]||s}
function uid(prefix='id'){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function route(){const hash=location.hash.replace(/^#/,'')||'home';const [page,id]=hash.split('/');return {page,id}}
function renderNav(){const current=route().page;const html=navItems.map(([id,icon,label])=>`<a class="nav-link ${current===id||current==='opportunity'&&id==='opportunities'?'active':''}" href="#${id}"><span class="nav-icon">${icon}</span><span>${label}</span></a>`).join('');document.querySelector('#desktop-nav').innerHTML=html;document.querySelector('#mobile-nav').innerHTML=html}
function render(){renderNav();const r=route();const main=document.querySelector('#main');if(r.page==='opportunities')main.innerHTML=opportunitiesPage();else if(r.page==='opportunity')main.innerHTML=opportunityPage(r.id);else if(r.page==='documents')main.innerHTML=documentsPage();else if(r.page==='profile')main.innerHTML=profilePage();else main.innerHTML=homePage();main.focus();bindPageEvents()}

function homePage(){
  const active=state.opportunities.filter(o=>!['closed'].includes(o.status));
  const submitted=active.filter(o=>o.status==='submitted').length;
  const preparing=active.filter(o=>['considering','preparing','ready'].includes(o.status)).length;
  const newCount=active.filter(o=>o.status==='new').length;
  const dated=active.filter(o=>o.deadline).sort((a,b)=>a.deadline.localeCompare(b.deadline));
  const next=dated[0];const days=next?daysTo(next.deadline):null;
  const urgent=days!==null&&days<=5;
  const basic=['CV','Académicos'];const have=new Set(state.documents.map(d=>d.category));const basicsReady=basic.every(x=>have.has(x));
  return `<section class="page">
    <div class="page-head"><div><div class="eyebrow">Inicio</div><h1>Hola, ${esc(state.profile.name||'José Luis')}</h1></div></div>
    <div class="reassurance"><div class="status-icon">${urgent?'!':'✓'}</div><div><strong>${urgent?'Hay una fecha próxima':'Todo está al día.'}</strong><p>${urgent?`${esc(next.title)} vence en ${days} días. El resto sigue guardado y en seguimiento.`:'No necesitas acordarte de todo. El portal mantiene tus procesos y documentos en orden.'}</p></div></div>
    <div class="home-grid">
      <article class="calm-card"><div class="card-icon green">▣</div><h2>Tus procesos</h2><div class="big-number">${active.length}</div><p>${submitted} enviados · ${preparing} avanzando</p><a class="card-link" href="#opportunities">Ver procesos →</a></article>
      <article class="calm-card"><div class="card-icon blue">▤</div><h2>Tus documentos</h2><div class="big-number">${state.documents.length}</div><p>${basicsReady?'Ya tienes lo básico guardado y reutilizable.':'Puedes ir reuniéndolos sin completar todo de una vez.'}</p><a class="card-link" href="#documents">Ver documentos →</a></article>
      <article class="calm-card"><div class="card-icon violet">✦</div><h2>Nuevas oportunidades</h2><div class="big-number">${newCount}</div><p>${newCount?'Para mirar cuando quieras.':'No hay novedades que revisar ahora.'}</p><a class="card-link" href="#opportunities">Ver oportunidades →</a></article>
    </div>
    <div class="subtle-row"><span>${next?`Próximo plazo registrado: <strong>${esc(next.title)}</strong> · ${fmtDate(next.deadline)}`:'No hay plazos confirmados todavía. Puedes añadirlos más adelante.'}</span><span class="small">Autoguardado activo</span></div>
  </section>`}

function opportunitiesPage(){
 const counts={};state.opportunities.forEach(o=>counts[o.status]=(counts[o.status]||0)+1);
 const filtered=state.opportunities.filter(o=>activeFilter==='all'||o.status===activeFilter).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));
 const filters=[['all','Todas'],['new','Nuevas'],['considering','En consideración'],['preparing','En preparación'],['ready','Listas'],['submitted','Enviadas'],['closed','Cerradas']];
 return `<section class="page"><div class="page-head"><div><div class="eyebrow">Procesos y radar</div><h1>Oportunidades</h1><p class="lede">Una sola lista desde que aparece una oportunidad hasta que termina el proceso.</p></div><button class="button primary" data-action="add-opportunity">+ Agregar</button></div>
 <div class="filters">${filters.map(([k,l])=>`<button class="pill ${activeFilter===k?'active':''}" data-filter="${k}">${l}${k!=='all'&&counts[k]?` · ${counts[k]}`:''}</button>`).join('')}</div>
 <div class="opportunity-list">${filtered.length?filtered.map(o=>opportunityRow(o)).join(''):'<div class="panel empty">No hay oportunidades en este estado.</div>'}</div></section>`}
function opportunityRow(o){return `<a class="opportunity-row" href="#opportunity/${o.id}"><div><div class="opportunity-title">${esc(o.title)}</div><div class="meta">${esc(o.institution)} · ${esc(o.country)}</div></div><div><span class="badge ${o.status}">${statusLabel(o.status)}</span></div><div><div class="small">${fmtDate(o.deadline)}</div><div class="meta">${o.deadline&&daysTo(o.deadline)>=0?`${daysTo(o.deadline)} días`:''}</div></div><div class="meta">${esc(o.funding||'')}</div><div>›</div></a>`}

function opportunityPage(id){
 const o=state.opportunities.find(x=>x.id===id);if(!o)return `<section class="page"><h1>No encontrada</h1><a href="#opportunities">Volver</a></section>`;
 syncRequirementStates(o);
 const reqs=o.requirements||[];const ready=reqs.filter(r=>r.state==='ready');const easy=reqs.filter(r=>r.state==='easy');const action=reqs.filter(r=>r.state==='action');
 return `<section class="page"><div class="detail-head"><div><a class="card-link" href="#opportunities">← Volver</a><div class="spacer"></div><span class="badge ${o.status}">${statusLabel(o.status)}</span><h1>${esc(o.title)}</h1><p class="lede">${esc(o.institution)} · ${esc(o.country)}</p><div class="detail-facts"><span class="fact">Fecha: ${fmtDate(o.deadline)}</span><span class="fact">Financiación: ${esc(o.funding||'Por verificar')}</span><span class="fact">Fuente: ${esc(o.source||'Manual')}</span></div></div><div class="toolbar"><button class="button" data-action="edit-opportunity" data-id="${o.id}">Editar</button>${o.sourceUrl?`<a class="button soft" href="${esc(o.sourceUrl)}" target="_blank" rel="noopener">Sitio oficial ↗</a>`:''}</div></div>
 <div class="section-grid"><div>
   <div class="panel"><h2>Por qué podría interesarte</h2><p class="muted">${esc(o.why||'Puedes añadir una nota breve cuando tengas más información.')}</p></div>
   ${action.length?`<div class="panel"><h2>Siguiente paso</h2><div class="requirements">${action.map(r=>reqHtml(o,r)).join('')}</div></div>`:''}
   ${easy.length?`<div class="panel"><h2>Fácil de resolver</h2><div class="requirements">${easy.map(r=>reqHtml(o,r)).join('')}</div></div>`:''}
   <div class="panel"><h2>Ya disponible</h2><div class="collapsed-summary">${ready.length} elemento${ready.length===1?'':'s'} listo${ready.length===1?'':'s'} y reutilizable${ready.length===1?'':'s'}.</div>${ready.length?`<details><summary class="card-link">Ver lo que ya está listo</summary><div class="requirements">${ready.map(r=>reqHtml(o,r)).join('')}</div></details>`:''}</div>
 </div><aside><div class="panel"><h2>Estado</h2><div class="spacer"></div><select class="select" data-action="change-status" data-id="${o.id}">${['new','considering','preparing','ready','submitted','closed'].map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${statusLabel(s)}</option>`).join('')}</select><p class="muted small">Puedes cambiarlo cuando quieras. Nada bloquea el guardado.</p></div><div class="panel"><h2>Notas</h2><p class="muted">${esc(o.notes||'Sin notas todavía.')}</p></div></aside></div></section>`}
function reqHtml(o,r){const symbol=r.state==='ready'?'✓':r.state==='easy'?'○':'!';let action='';if(r.state==='easy'&&r.id==='motivation')action=`<button class="button soft" data-action="motivation" data-id="${o.id}">Crear borrador</button>`;else if(r.state==='action'&&r.id==='english')action=`<button class="button soft" data-action="english-options" data-id="${o.id}">Ver opciones</button>`;else if(r.state!=='ready')action=`<button class="button" data-action="resolve-requirement" data-opp="${o.id}" data-req="${r.id}">Resolver</button>`;return `<div class="req ${r.state}"><div class="req-main"><span class="req-dot">${symbol}</span><div><strong>${esc(r.label)}</strong><div class="meta">${r.state==='ready'?'Ya lo tienes':r.state==='easy'?'Se puede preparar aquí':'Requiere una acción externa o un dato adicional'}</div></div></div>${action}</div>`}
function syncRequirementStates(o){(o.requirements||[]).forEach(r=>{if(r.type==='document'&&r.category){r.state=state.documents.some(d=>d.category===r.category)?'ready':'action'}})}

function documentsPage(){const cats=['Todos','CV','Académicos','Idiomas','Recomendaciones','Muestras','Otros'];return `<section class="page"><div class="page-head"><div><div class="eyebrow">Dossier maestro</div><h1>Documentos</h1><p class="lede">Una sola copia útil de cada documento, lista para reutilizar.</p></div><button class="button primary" data-action="upload-docs">+ Subir documento</button></div><div class="docs-grid"><aside class="panel"><h3>Categorías</h3><div class="category-list">${cats.map((c,i)=>`<div class="category-item ${i===0?'active':''}">${c}</div>`).join('')}</div><div class="spacer"></div><button class="button soft" data-action="generate-cv">Crear / actualizar CV</button></aside><div class="panel">${state.documents.length?`<table class="doc-table"><thead><tr><th>Documento</th><th>Categoría</th><th>Versión</th><th></th></tr></thead><tbody>${state.documents.map(d=>`<tr><td><strong>${esc(d.name)}</strong><div class="meta">Actualizado ${fmtDate(d.updated)}</div></td><td>${esc(d.category)}</td><td>v${d.version}</td><td><button class="quiet-button danger" data-action="delete-doc" data-id="${d.id}">Quitar</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Todavía no hay documentos. Puedes subirlos cuando quieras.</div>'}</div></div></section>`}

function profilePage(){const p=state.profile;return `<section class="page"><div class="page-head"><div><div class="eyebrow">Fuente reutilizable</div><h1>Perfil</h1><p class="lede">Lo que el sistema ya sabe para no volver a preguntártelo.</p></div><button class="button primary" data-action="edit-profile">Editar</button></div><div class="profile-grid">
 ${profileBox('Información personal',[['Nombre',p.name],['Email',p.email||'Por completar'],['Teléfono',p.phone||'Por completar'],['Ubicación',p.city||'Por completar']])}
 ${profileBox('Formación',[['Estudios',p.education||'Por completar']])}
 ${profileBox('Experiencia',[['Actual',p.experience||'Puedes añadirla cuando quieras']])}
 ${profileBox('Idiomas',[['Idiomas',p.languages||'Por completar']])}
 ${profileBox('Habilidades',[['Perfil',p.skills||'Por completar']])}
 ${profileBox('Referencias',[['Contactos',p.references||'Todavía no añadidas']])}
 </div></section>`}
function profileBox(title,rows){return `<article class="panel profile-section"><h2>${title}</h2><div class="profile-list">${rows.map(([a,b])=>`<div class="profile-line"><span>${a}</span><strong>${esc(b)}</strong></div>`).join('')}</div></article>`}

function bindPageEvents(){
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;render()});
 document.querySelectorAll('[data-action]').forEach(el=>{if(el.closest('#desktop-nav,#mobile-nav'))return;el.addEventListener('click',handleAction)});
}
function handleAction(e){const a=e.currentTarget.dataset.action;if(a==='add-opportunity')openOpportunityForm();if(a==='edit-opportunity')openOpportunityForm(e.currentTarget.dataset.id);if(a==='change-status'){const o=state.opportunities.find(x=>x.id===e.currentTarget.dataset.id);o.status=e.currentTarget.value;saveState(`Estado actualizado: ${o.title}`);render()}if(a==='upload-docs')document.querySelector('#file-input').click();if(a==='delete-doc'){state.documents=state.documents.filter(d=>d.id!==e.currentTarget.dataset.id);saveState('Documento retirado del dossier local');render()}if(a==='edit-profile')openProfileForm();if(a==='generate-cv')openCvGenerator();if(a==='motivation')openMotivation(e.currentTarget.dataset.id);if(a==='english-options')openEnglishOptions();if(a==='resolve-requirement')openRequirementResolve(e.currentTarget.dataset.opp,e.currentTarget.dataset.req);if(a==='reset-demo'){if(confirm('¿Reiniciar los datos locales de este navegador?')){state=clone(seedState);saveState();render();toast('Datos locales reiniciados')}}}

function openModal(title,body,footer=''){const m=document.querySelector('#modal');document.querySelector('#modal-content').innerHTML=`<div class="modal-card"><div class="modal-head"><h2>${title}</h2><button class="close" data-close>×</button></div>${body}${footer}</div>`;m.showModal();m.querySelector('[data-close]').onclick=()=>m.close();m.onclick=e=>{if(e.target===m)m.close()}}
function openOpportunityForm(id){const o=id?state.opportunities.find(x=>x.id===id):{title:'',institution:'',country:'',funding:'',deadline:'',sourceUrl:'',why:'',notes:'',status:'new'};openModal(id?'Editar oportunidad':'Agregar oportunidad',`<form id="op-form" class="form-grid">
 ${field('Título','title',o.title,true)}${field('Institución','institution',o.institution)}${field('País','country',o.country)}${field('Fecha límite','deadline',o.deadline,'date')}${field('Financiación','funding',o.funding)}${field('Link oficial','sourceUrl',o.sourceUrl,'url')}${textarea('Por qué puede interesar','why',o.why)}${textarea('Notas','notes',o.notes)}
 <div class="modal-actions"><button type="button" class="button" data-cancel>Ahora no</button><button class="button primary" type="submit">Guardar</button></div></form>`);const f=document.querySelector('#op-form');f.querySelector('[data-cancel]').onclick=()=>document.querySelector('#modal').close();f.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));if(id)Object.assign(o,d);else state.opportunities.unshift({id:uid('opp'),...d,status:'new',source:'Manual',requirements:[]});saveState(id?`Oportunidad actualizada: ${o.title}`:`Nueva oportunidad añadida: ${d.title}`);document.querySelector('#modal').close();render()}}
function field(label,name,value='',requiredOrType=false,typeMaybe='text'){let required=false,type='text';if(requiredOrType===true)required=true;else if(typeof requiredOrType==='string')type=requiredOrType;if(typeMaybe!=='text')type=typeMaybe;return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value||'')}" ${required?'required':''}></div>`}
function textarea(label,name,value=''){return `<div class="field"><label>${label}</label><textarea name="${name}">${esc(value||'')}</textarea></div>`}
function openProfileForm(){const p=state.profile;openModal('Editar perfil',`<form id="profile-form" class="form-grid">${field('Nombre','name',p.name)}${field('Email','email',p.email,'email')}${field('Teléfono','phone',p.phone)}${field('Ubicación','city',p.city)}${textarea('Formación','education',p.education)}${textarea('Experiencia actual','experience',p.experience)}${textarea('Idiomas','languages',p.languages)}${textarea('Habilidades','skills',p.skills)}${textarea('Referencias','references',p.references)}<div class="modal-actions"><button type="button" class="button" data-cancel>Ahora no</button><button class="button primary">Guardar</button></div></form>`);const f=document.querySelector('#profile-form');f.querySelector('[data-cancel]').onclick=()=>document.querySelector('#modal').close();f.onsubmit=e=>{e.preventDefault();Object.assign(state.profile,Object.fromEntries(new FormData(f)));saveState('Perfil actualizado');document.querySelector('#modal').close();render()}}

function openCvGenerator(){const p=state.profile;openModal('Crear o actualizar CV',`<p class="muted">El sistema reutiliza lo que ya sabe. Puedes escribir la experiencia actual de manera informal y corregirla después.</p><form id="cv-form" class="form-grid">${textarea('¿Qué estás haciendo actualmente?','experience',p.experience)}<div class="field"><label>Versión</label><select name="variant"><option value="professional">Profesional</option><option value="academic">Académica</option><option value="short">1 página</option></select></div><div class="modal-actions"><button type="button" class="button" data-cancel>Ahora no</button><button class="button primary">Generar</button></div></form>`);const f=document.querySelector('#cv-form');f.querySelector('[data-cancel]').onclick=()=>document.querySelector('#modal').close();f.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));state.profile.experience=d.experience;const text=`${state.profile.name}\n${state.profile.education}\n\nEXPERIENCIA\n${d.experience}\n\nIDIOMAS\n${state.profile.languages}\n\nHABILIDADES\n${state.profile.skills}`;downloadText(`CV_${state.profile.name.replace(/\s+/g,'_')}_${d.variant}.txt`,text);const prev=state.documents.filter(x=>x.category==='CV');state.documents.unshift({id:uid('doc'),name:`CV_${d.variant}.txt`,category:'CV',version:(Math.max(0,...prev.map(x=>x.version||1))+1),status:'ready',size:text.length,lastModified:Date.now(),updated:new Date().toISOString().slice(0,10)});saveState('Nueva versión de CV generada');document.querySelector('#modal').close();render()}}
function openMotivation(id){const o=state.opportunities.find(x=>x.id===id);const draft=`Estimado equipo de selección:\n\nMe interesa ${o.title} porque ${o.why||'encaja con mi trayectoria y próximos pasos profesionales'}. Mi formación en ${state.profile.education||'sociología'} y mi experiencia ${state.profile.experience||'profesional'} pueden aportar una base relevante para esta oportunidad.\n\nQuisiera profundizar esta motivación con ejemplos concretos antes de enviar la versión final.`;openModal('Borrador de carta',`<p class="muted">Borrador de trabajo. No inventa logros; completa sólo con información conocida.</p><div class="field"><textarea id="motivation-text">${esc(draft)}</textarea></div><div class="modal-actions"><button class="button" data-close2>Dejar para después</button><button class="button primary" data-download>Guardar borrador</button></div>`);document.querySelector('[data-close2]').onclick=()=>document.querySelector('#modal').close();document.querySelector('[data-download]').onclick=()=>{downloadText(`Carta_motivacion_${o.id}.txt`,document.querySelector('#motivation-text').value);const r=o.requirements.find(x=>x.id==='motivation');if(r)r.state='ready';saveState(`Borrador de motivación creado: ${o.title}`);document.querySelector('#modal').close();render()}}
function openEnglishOptions(){openModal('Opciones para acreditar inglés',`<p>Primero hay que verificar qué acepta <strong>esta convocatoria concreta</strong>. El portal no asumirá que un test sirve universalmente.</p><div class="requirements"><div class="req easy"><div class="req-main"><span class="req-dot">1</span><div><strong>Ver requisitos oficiales</strong><div class="meta">Confirmar IELTS, TOEFL, Duolingo, Cambridge u otra exención.</div></div></div></div><div class="req easy"><div class="req-main"><span class="req-dot">2</span><div><strong>Elegir la opción de menor fricción</strong><div class="meta">Priorizar coste, disponibilidad, modalidad y tiempo de resultados.</div></div></div></div></div><div class="modal-actions"><button class="button primary" data-close2>Entendido</button></div>`);document.querySelector('[data-close2]').onclick=()=>document.querySelector('#modal').close()}
function openRequirementResolve(oppId,reqId){const o=state.opportunities.find(x=>x.id===oppId);const r=o?.requirements.find(x=>x.id===reqId);if(!r)return;openModal('Resolver cuando quieras',`<p class="muted">Puedes marcarlo como listo ahora o dejarlo exactamente como está. Nada se pierde.</p><div class="req action"><div class="req-main"><span class="req-dot">!</span><div><strong>${esc(r.label)}</strong><div class="meta">Si ya lo resolviste fuera del portal, márcalo listo.</div></div></div></div><div class="modal-actions"><button class="button" data-close2>Más tarde</button><button class="button primary" data-ready>Marcar listo</button></div>`);document.querySelector('[data-close2]').onclick=()=>document.querySelector('#modal').close();document.querySelector('[data-ready]').onclick=()=>{r.state='ready';saveState(`Requisito resuelto: ${r.label}`);document.querySelector('#modal').close();render()}}

function downloadText(name,text){const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function toast(msg){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2200)}

document.querySelector('#file-input').addEventListener('change',e=>{for(const file of e.target.files){const same=state.documents.find(d=>d.name===file.name&&d.size===file.size&&d.lastModified===file.lastModified);if(same){toast(`${file.name}: ya existe`);continue}const base=state.documents.filter(d=>d.name===file.name);state.documents.unshift({id:uid('doc'),name:file.name,category:guessCategory(file.name),version:Math.max(0,...base.map(x=>x.version||1))+1,status:'ready',size:file.size,lastModified:file.lastModified,updated:new Date().toISOString().slice(0,10)})}saveState('Dossier actualizado');e.target.value='';render()});
function guessCategory(name){const n=name.toLowerCase();if(n.includes('cv')||n.includes('curric'))return 'CV';if(n.includes('ielts')||n.includes('toefl')||n.includes('english')||n.includes('idioma'))return 'Idiomas';if(n.includes('recommend')||n.includes('carta'))return 'Recomendaciones';if(n.includes('transcript')||n.includes('titulo')||n.includes('diplom')||n.includes('nota'))return 'Académicos';return 'Otros'}

document.querySelector('#global-search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q)return;const o=state.opportunities.find(x=>(x.title+' '+x.institution+' '+x.country).toLowerCase().includes(q));if(o)location.hash=`opportunity/${o.id}`;else if(state.documents.some(d=>d.name.toLowerCase().includes(q)))location.hash='documents'});
window.addEventListener('hashchange',render);render();
