const STORAGE_KEY='joseluis-portal-v2';
const seed={
 profile:{name:'José Luis',email:'',phone:'',city:'Chile',education:'Sociología',experience:'',languages:'Español; Inglés por completar',skills:'Investigación social; análisis; redacción',references:''},
 documents:[
  {id:'d1',name:'CV_actual.pdf',category:'CV',version:1,status:'ready',updated:'2026-08-31'},
  {id:'d2',name:'Título_profesional.pdf',category:'Estudios',version:1,status:'ready',updated:'2026-08-31'},
  {id:'d3',name:'Transcript.pdf',category:'Estudios',version:1,status:'ready',updated:'2026-08-31'}
 ],
 opportunities:[
  {id:'opp-daad',title:'DAAD',institution:'DAAD',country:'Alemania',funding:'Por verificar',deadline:'',status:'new',sourceUrl:'https://www.daad.de/en/studying-in-germany/scholarships/',why:'Programa por revisar.',notes:'',requirements:[{id:'cv',label:'CV',type:'document',category:'CV',state:'ready'},{id:'degree',label:'Título',type:'document',category:'Estudios',state:'ready'},{id:'motivation',label:'Carta de motivación',type:'easy',state:'easy'},{id:'english',label:'Inglés',type:'action',state:'action'}]},
  {id:'opp-barcelona',title:'Barcelona',institution:'Programa por definir',country:'España',funding:'Por verificar',deadline:'',status:'considering',sourceUrl:'',why:'Oportunidad por concretar.',notes:'',requirements:[{id:'cv',label:'CV',type:'document',category:'CV',state:'ready'},{id:'degree',label:'Título',type:'document',category:'Estudios',state:'ready'},{id:'transcript',label:'Transcript',type:'document',category:'Estudios',state:'ready'},{id:'motivation',label:'Carta de motivación',type:'easy',state:'easy'}]},
  {id:'opp-erasmus',title:'Erasmus+',institution:'Unión Europea',country:'Europa',funding:'Según programa',deadline:'',status:'new',sourceUrl:'https://erasmus-plus.ec.europa.eu/',why:'Opción por revisar.',notes:'',requirements:[{id:'cv',label:'CV',type:'document',category:'CV',state:'ready'}]},
  {id:'opp-fulbright',title:'Fulbright',institution:'Fulbright',country:'Internacional',funding:'Según convocatoria',deadline:'',status:'new',sourceUrl:'https://foreign.fulbrightonline.org/',why:'Opción por revisar.',notes:'',requirements:[{id:'cv',label:'CV',type:'document',category:'CV',state:'ready'},{id:'english',label:'Inglés',type:'action',state:'action'}]}
 ],history:[]
};
let state=load(),filter='all';
const nav=[['home','⌂','Inicio'],['opportunities','◉','Oportunidades'],['documents','▢','Documentos'],['profile','♙','Perfil']];
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||clone(seed)}catch{return clone(seed)}}
function save(msg){if(msg)state.history.unshift({at:new Date().toISOString(),text:msg});localStorage.setItem(STORAGE_KEY,JSON.stringify(state));toast('Guardado')}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function route(){const [page,id]=((location.hash||'#home').slice(1)).split('/');return{page,id}}
function days(v){return v?Math.ceil((new Date(v+'T23:59:59')-new Date())/86400000):null}
function date(v){if(!v)return'—';return new Intl.DateTimeFormat('es',{day:'numeric',month:'short'}).format(new Date(v+'T12:00:00'))}
function status(s){return{new:'Nueva',considering:'Mirando',preparing:'Preparando',ready:'Lista',submitted:'Enviada',closed:'Cerrada'}[s]||s}
function uid(p='id'){return p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,6)}
function renderNav(){const r=route().page;const html=nav.map(([id,i,l])=>`<a class="nav-link ${(r===id||(r==='opportunity'&&id==='opportunities'))?'active':''}" href="#${id}"><span>${i}</span><span>${l}</span></a>`).join('');document.querySelector('#desktop-nav').innerHTML=html;document.querySelector('#mobile-nav').innerHTML=html}
function render(){renderNav();const r=route(),m=document.querySelector('#main');m.innerHTML=r.page==='opportunities'?opportunities():r.page==='opportunity'?opportunity(r.id):r.page==='documents'?documents():r.page==='profile'?profile():home();bind()}
function sync(o){(o.requirements||[]).forEach(r=>{if(r.type==='document')r.state=state.documents.some(d=>d.category===r.category)?'ready':'action'})}
function home(){const active=state.opportunities.filter(o=>o.status!=='closed'),newN=active.filter(o=>o.status==='new').length,dated=active.filter(o=>o.deadline).sort((a,b)=>a.deadline.localeCompare(b.deadline)),next=dated[0],d=next?days(next.deadline):null,urgent=d!==null&&d<=5;return `<section class="app-page home-screen"><header class="simple-head"><h1>${esc(state.profile.name||'José Luis')}</h1></header><div class="app-status ${urgent?'urgent':''}"><span>${urgent?'!':'✓'}</span><strong>${urgent?'Plazo próximo':'Todo al día'}</strong></div><div class="metric-grid"><a class="metric-card" href="#opportunities"><b>${active.length}</b><span>Procesos</span></a><a class="metric-card" href="#documents"><b>${state.documents.length}</b><span>Documentos</span></a></div><a class="wide-card" href="#opportunities"><span class="spark">✦</span><b>${newN} nuevas</b><span>›</span></a>${next?`<div class="next-line"><span>Próximo plazo</span><b>${d>=0?d+' días':date(next.deadline)}</b></div>`:''}</section>`}
function opportunities(){const list=state.opportunities.filter(o=>filter==='all'||o.status===filter).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));const fs=[['all','Todas'],['new','Nuevas'],['considering','Mirando'],['preparing','Preparando'],['submitted','Enviadas']];return `<section class="app-page"><header class="simple-head row"><h1>Oportunidades</h1><button class="round-add" data-action="add-opportunity" aria-label="Agregar">+</button></header><div class="chip-row">${fs.map(([k,l])=>`<button class="chip ${filter===k?'active':''}" data-filter="${k}">${l}</button>`).join('')}</div><div class="app-list">${list.map(o=>oppRow(o)).join('')||'<div class="blank">Nada aquí</div>'}</div></section>`}
function oppRow(o){const d=o.deadline?days(o.deadline):null;return `<a class="app-row" href="#opportunity/${o.id}"><div><b>${esc(o.title)}</b><span>${esc(o.country)}${o.institution&&o.institution!==o.title?' · '+esc(o.institution):''}</span></div><div class="row-end"><span class="mini-state ${o.status}">${o.deadline&&d>=0?d+' d':status(o.status)}</span><i>›</i></div></a>`}
function opportunity(id){const o=state.opportunities.find(x=>x.id===id);if(!o)return'<section class="app-page"><h1>No encontrada</h1></section>';sync(o);const rs=o.requirements||[],ready=rs.filter(r=>r.state==='ready'),easy=rs.filter(r=>r.state==='easy'),action=rs.filter(r=>r.state==='action');const first=action[0]||easy[0];return `<section class="app-page detail-screen"><a class="back" href="#opportunities">‹ Oportunidades</a><header class="detail-title"><div><h1>${esc(o.title)}</h1><span>${esc(o.country)}</span></div><button class="icon-edit" data-action="edit-opportunity" data-id="${o.id}">•••</button></header><div class="fact-strip"><div><span>Financiación</span><b>${esc(o.funding||'—')}</b></div><div><span>Plazo</span><b>${o.deadline?date(o.deadline):'—'}</b></div></div><div class="state-counters"><div class="ok"><b>${ready.length}</b><span>Listo</span></div><div class="easy"><b>${easy.length}</b><span>Fácil</span></div><div class="todo"><b>${action.length}</b><span>Por resolver</span></div></div>${first?`<button class="continue-card" data-action="open-requirement" data-opp="${o.id}" data-req="${first.id}"><span><small>Siguiente</small><b>${esc(first.label)}</b></span><i>›</i></button>`:'<div class="done-card">✓ Listo</div>'}<button class="details-toggle" data-action="toggle-details">Detalles <span>›</span></button><div id="detail-extra" class="detail-extra hidden"><div class="compact-list">${rs.map(r=>`<button class="compact-item" data-action="open-requirement" data-opp="${o.id}" data-req="${r.id}"><span>${r.state==='ready'?'✓':r.state==='easy'?'○':'!'}</span><b>${esc(r.label)}</b><i>›</i></button>`).join('')}</div><div class="status-line"><span>Estado</span><select data-action="change-status" data-id="${o.id}">${['new','considering','preparing','ready','submitted','closed'].map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${status(s)}</option>`).join('')}</select></div>${o.sourceUrl?`<a class="external" href="${esc(o.sourceUrl)}" target="_blank" rel="noopener">Sitio oficial ↗</a>`:''}</div></section>`}
function documents(){const cats=['CV','Estudios','Idiomas','Recomendaciones','Muestras','Otros'];return `<section class="app-page"><header class="simple-head row"><h1>Documentos</h1><button class="round-add" data-action="upload-docs">+</button></header><div class="search-mini"><span>⌕</span><input id="doc-search" placeholder="Buscar" /></div><div class="app-list categories">${cats.map(c=>{const n=state.documents.filter(d=>d.category===c).length;return `<button class="app-row category-row" data-action="open-category" data-category="${c}"><div><b>${c}</b><span>${n?n+' guardado'+(n===1?'':'s'):'Vacío'}</span></div><div class="row-end"><b>${n}</b><i>›</i></div></button>`}).join('')}</div><div id="doc-results"></div></section>`}
function profile(){const p=state.profile;const blocks=[['Datos',p.email||p.phone||p.city||'Sin completar'],['Estudios',p.education||'—'],['Experiencia',p.experience||'—'],['Idiomas',p.languages||'—'],['Habilidades',p.skills||'—'],['Referencias',p.references||'—']];return `<section class="app-page"><header class="simple-head row"><h1>Perfil</h1><button class="round-add edit" data-action="edit-profile">✎</button></header><div class="profile-hero"><div class="avatar big">JL</div><div><b>${esc(p.name)}</b><span>${esc(p.education||'')}</span></div></div><div class="app-list">${blocks.map(([k,v])=>`<button class="app-row profile-row" data-action="edit-profile"><div><b>${k}</b><span>${esc(String(v).split(';')[0])}</span></div><i>›</i></button>`).join('')}</div><button class="wide-action" data-action="generate-cv">Generar CV</button></section>`}
function bind(){document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=e=>action(e.currentTarget));const ds=document.querySelector('#doc-search');if(ds)ds.oninput=()=>showDocs(ds.value)}
function action(el){const a=el.dataset.action;if(a==='add-opportunity')return editOpportunity();if(a==='edit-opportunity')return editOpportunity(state.opportunities.find(o=>o.id===el.dataset.id));if(a==='change-status'){const o=state.opportunities.find(x=>x.id===el.dataset.id);o.status=el.value;save('Estado actualizado');render();return}if(a==='toggle-details'){document.querySelector('#detail-extra').classList.toggle('hidden');return}if(a==='open-requirement')return openRequirement(el.dataset.opp,el.dataset.req);if(a==='upload-docs')return document.querySelector('#file-input').click();if(a==='open-category')return showDocs('',el.dataset.category);if(a==='edit-profile')return editProfile();if(a==='generate-cv')return generateCV()}
function openRequirement(oid,rid){const o=state.opportunities.find(x=>x.id===oid),r=(o.requirements||[]).find(x=>x.id===rid);if(!r)return;if(r.state==='ready')return modal(`<h2>${esc(r.label)}</h2><div class="big-ok">✓</div><p class="center">Listo</p>`);if(r.id==='motivation')return modal(`<h2>Carta de motivación</h2><textarea id="motivation-text" class="big-text">${esc(`Me interesa ${o.title} porque conecta con mi experiencia e intereses. Adaptar este borrador antes de enviarlo.`)}</textarea><button class="wide-action" onclick="document.querySelector('#modal').close()">Guardar</button>`);if(r.id==='english')return modal(`<h2>Inglés</h2><div class="choice-list"><a href="https://www.ielts.org/" target="_blank">IELTS <span>›</span></a><a href="https://www.ets.org/toefl.html" target="_blank">TOEFL <span>›</span></a><a href="https://englishtest.duolingo.com/" target="_blank">Duolingo <span>›</span></a></div><p class="tiny">Verificar qué acepta la convocatoria.</p>`);modal(`<h2>${esc(r.label)}</h2><button class="wide-action" onclick="document.querySelector('#file-input').click();document.querySelector('#modal').close()">Subir documento</button>`)}
function showDocs(q='',cat=''){const box=document.querySelector('#doc-results');if(!box)return;const list=state.documents.filter(d=>(!cat||d.category===cat)&&(!q||d.name.toLowerCase().includes(q.toLowerCase())));box.innerHTML=`<div class="doc-pop ${list.length?'':'hidden'}">${list.map(d=>`<div class="file-row"><span>▤</span><div><b>${esc(d.name)}</b><small>${esc(d.category)}</small></div></div>`).join('')}</div>`}
function editOpportunity(o){const x=o||{id:uid('opp'),title:'',institution:'',country:'',funding:'',deadline:'',status:'new',sourceUrl:'',why:'',notes:'',requirements:[]};modal(`<h2>${o?'Editar':'Nueva oportunidad'}</h2><div class="form-grid"><label>Título<input id="f-title" value="${esc(x.title)}"></label><label>Institución<input id="f-inst" value="${esc(x.institution)}"></label><label>País<input id="f-country" value="${esc(x.country)}"></label><label>Plazo<input id="f-deadline" type="date" value="${esc(x.deadline)}"></label><label>Financiación<input id="f-funding" value="${esc(x.funding)}"></label><label>Link<input id="f-url" value="${esc(x.sourceUrl)}"></label></div><button id="save-opp" class="wide-action">Guardar</button>`);document.querySelector('#save-opp').onclick=()=>{x.title=document.querySelector('#f-title').value||'Sin título';x.institution=document.querySelector('#f-inst').value;x.country=document.querySelector('#f-country').value;x.deadline=document.querySelector('#f-deadline').value;x.funding=document.querySelector('#f-funding').value;x.sourceUrl=document.querySelector('#f-url').value;if(!o)state.opportunities.unshift(x);save('Oportunidad guardada');document.querySelector('#modal').close();location.hash='opportunity/'+x.id;render()}}
function editProfile(){const p=state.profile;modal(`<h2>Perfil</h2><div class="form-grid"><label>Nombre<input id="p-name" value="${esc(p.name)}"></label><label>Email<input id="p-email" value="${esc(p.email)}"></label><label>Ciudad / país<input id="p-city" value="${esc(p.city)}"></label><label>Estudios<input id="p-edu" value="${esc(p.education)}"></label><label>Experiencia<textarea id="p-exp">${esc(p.experience)}</textarea></label><label>Idiomas<input id="p-lang" value="${esc(p.languages)}"></label><label>Habilidades<input id="p-skills" value="${esc(p.skills)}"></label></div><button id="save-profile" class="wide-action">Guardar</button>`);document.querySelector('#save-profile').onclick=()=>{p.name=document.querySelector('#p-name').value;p.email=document.querySelector('#p-email').value;p.city=document.querySelector('#p-city').value;p.education=document.querySelector('#p-edu').value;p.experience=document.querySelector('#p-exp').value;p.languages=document.querySelector('#p-lang').value;p.skills=document.querySelector('#p-skills').value;save('Perfil guardado');document.querySelector('#modal').close();render()}}
function generateCV(){const p=state.profile,txt=`${p.name}\n\n${p.education}\n${p.experience}\n${p.languages}\n${p.skills}`;const blob=new Blob([txt],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='CV_Jose_Luis.txt';a.click();URL.revokeObjectURL(a.href);save('CV generado')}
function guess(name){const n=name.toLowerCase();if(n.includes('cv')||n.includes('curric'))return'CV';if(n.includes('ielts')||n.includes('toefl')||n.includes('idioma')||n.includes('english'))return'Idiomas';if(n.includes('recommend')||n.includes('recomend'))return'Recomendaciones';if(n.includes('transcript')||n.includes('titulo')||n.includes('diplom')||n.includes('nota'))return'Estudios';return'Otros'}
document.querySelector('#file-input').onchange=e=>{[...e.target.files].forEach(f=>{const duplicate=state.documents.some(d=>d.name===f.name&&d.size===f.size);if(!duplicate)state.documents.push({id:uid('doc'),name:f.name,category:guess(f.name),version:1,status:'ready',size:f.size,updated:new Date().toISOString().slice(0,10)})});save('Documentos actualizados');e.target.value='';render()}
function modal(html){const d=document.querySelector('#modal');document.querySelector('#modal-content').innerHTML=`<div class="modal-card"><button class="modal-close" onclick="document.querySelector('#modal').close()">×</button>${html}</div>`;d.showModal()}
function toast(t){let x=document.querySelector('.toast');if(x)x.remove();x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1200)}
document.querySelector('#global-search').oninput=e=>{const q=e.target.value.toLowerCase().trim();if(!q)return;const o=state.opportunities.find(x=>(x.title+' '+x.country+' '+x.institution).toLowerCase().includes(q));if(o)location.hash='opportunity/'+o.id;else if(state.documents.some(d=>d.name.toLowerCase().includes(q)))location.hash='documents'};
document.addEventListener('click',e=>{const r=e.target.closest('[data-action="reset-demo"]');if(r&&confirm('¿Reiniciar los datos locales?')){localStorage.removeItem(STORAGE_KEY);state=clone(seed);render()}});
window.addEventListener('hashchange',render);render();