const STORAGE_KEY='weekly-1on1-prep-v0';
const seed={
  meetings:[{id:'2026-09-07',date:'2026-09-07',manager:'Lucas',status:'preparing',agenda:['caqtus-mapping-deck','error-budgets-v0','portfolio-2026-09-07'],asks:['ask-caqtus-direction','ask-eb-direction']}],
  topics:[
    {id:'caqtus-mapping',title:'CAQTUS Mapping',status:'active',priority:'high',latestUpdate:'Baseline and simulator are mature enough; next value is alignment and prediction-to-test.',nextAction:'Validate authority with Julien and freeze one prediction-to-test path.',needFromLucas:'Confirm direction and alignment sequence with Julien/System Performance.',includeInNext1on1:true},
    {id:'error-budgets',title:'Error Budgets',status:'active',priority:'high',latestUpdate:'V0 dashboard, traceability and SPECS/results separation are demonstrable.',nextAction:'Prepare the exact review ask and show only the mature V0.',needFromLucas:'Review whether the general direction is right before scaling.',includeInNext1on1:true},
    {id:'portfolio',title:'Portfolio / Other topics',status:'active',priority:'medium',latestUpdate:'Secondary workstreams can be compressed into a one-page status.',nextAction:'Refresh MAGMA, CAQTUS depumping and Kurdak/Paper Club bullets.',needFromLucas:'None unless one secondary topic becomes decision-worthy.',includeInNext1on1:true},
    {id:'magma',title:'MAGMA',status:'waiting',priority:'medium',latestUpdate:'Prepared context and bibliography; waiting for the appropriate checkpoint.',nextAction:'Update after checkpoint.',needFromLucas:'',includeInNext1on1:false}
  ],
  deliverables:[
    {id:'caqtus-mapping-deck',topicId:'caqtus-mapping',title:'CAQTUS Mapping — Processing alignment mini-deck',type:'presentation',maturity:'candidate',version:'v0.1',targetMeetingId:'2026-09-07',objective:'Show current understanding, confirmed vs to-validate, and one simulation → observable → test path.',missingDependencies:['Validate authoritative baseline with Julien','Choose one prediction-to-test path'],reviewAsk:'Confirm direction and alignment sequence.',link:''},
    {id:'error-budgets-v0',topicId:'error-budgets',title:'Error Budgets V0 — dashboard + review note',type:'dashboard',maturity:'ready-to-show',version:'v0',targetMeetingId:'2026-09-07',objective:'Show the real V0 and get a direction review before scaling.',missingDependencies:['Polish exact review ask'],reviewAsk:'Is this the right direction to continue?',link:'https://github.com/ortiz-luis/error-budgets'},
    {id:'portfolio-2026-09-07',topicId:'portfolio',title:'Weekly portfolio status — 2026-09-07',type:'one-pager',maturity:'candidate',version:'v0.1',targetMeetingId:'2026-09-07',objective:'Cover secondary workstreams in under two minutes.',missingDependencies:['Refresh secondary-topic status'],reviewAsk:'',link:''}
  ],
  decisions:[
    {id:'ask-caqtus-direction',topicId:'caqtus-mapping',meetingId:'2026-09-07',question:'Does this look like the right Processing-side alignment before going to System Performance?',status:'planned'},
    {id:'ask-eb-direction',topicId:'error-budgets',meetingId:'2026-09-07',question:'Is the Error Budgets V0 direction right before I scale the system?',status:'planned'}
  ],
  history:[]
};
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||clone(seed)}catch{return clone(seed)}}
let state=load();
const $=q=>document.querySelector(q);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=[['home','⌂','Inicio'],['next','◎','Próximo 1:1'],['topics','◉','Temas'],['deliverables','▢','Entregables'],['history','↺','Histórico']];
function route(){const [page='home',id]=location.hash.replace(/^#/,'').split('/');return {page:page||'home',id}}
function renderNav(){const p=route().page;const html=nav.map(([id,ic,label])=>`<a class="nav-link ${p===id?'active':''}" href="#${id}"><span class="nav-icon">${ic}</span><span>${label}</span></a>`).join('');$('#desktop-nav').innerHTML=html;$('#mobile-nav').innerHTML=html}
function maturityLabel(x){return {'work-in-progress':'En preparación',candidate:'Candidato','ready-to-show':'Listo para mostrar','shown-reviewed':'Mostrado / revisado','archived-superseded':'Archivado'}[x]||x}
function typeLabel(x){return {presentation:'Presentación',dashboard:'Dashboard','one-pager':'One-pager',pdf:'PDF',demo:'Demo',report:'Informe'}[x]||x}
function meeting(){return state.meetings.find(m=>m.status!=='completed')||state.meetings[0]}
function homePage(){const m=meeting();const ready=state.deliverables.filter(d=>d.targetMeetingId===m.id&&d.maturity==='ready-to-show');const cooking=state.deliverables.filter(d=>d.targetMeetingId===m.id&&d.maturity==='candidate');const asks=state.decisions.filter(d=>d.meetingId===m.id&&d.status==='planned');return `<section class="app-page home-screen"><div class="simple-head"><h1>1:1 con Lucas</h1></div><div class="app-status"><span>✓</span><strong>Preparando ${fmtDate(m.date)}</strong></div><div class="metric-grid"><a href="#deliverables" class="metric-card"><b>${ready.length}</b><span>Listos para mostrar</span></a><a href="#next" class="metric-card"><b>${asks.length}</b><span>Decisiones para Lucas</span></a></div><div class="section-head"><h2>Ready for next 1:1</h2></div>${ready.length?listDeliverables(ready):`<div class="blank">Todavía no hay entregables marcados como listos.</div>`}<div class="section-head"><h2>Still cooking</h2></div>${listDeliverables(cooking)}<div class="section-head"><h2>Needs Lucas</h2></div>${asks.map(a=>`<div class="wide-card"><span class="spark">?</span><div><b>${esc(a.question)}</b></div><span>›</span></div>`).join('')}</section>`}
function nextPage(){const m=meeting();const ordered=m.agenda.map(id=>state.deliverables.find(d=>d.id===id)).filter(Boolean);return `<section class="app-page"><div class="simple-head"><h1>Próximo 1:1</h1><p class="subtle">${fmtDate(m.date)}</p></div><div class="section-head"><h2>Orden recomendado</h2></div>${ordered.map((d,i)=>`<a class="app-row" href="#deliverables/${d.id}"><div><strong>${i+1}. ${esc(d.title)}</strong><span>${typeLabel(d.type)} · ${maturityLabel(d.maturity)}</span></div><div class="row-end"><i>›</i></div></a>`).join('')}<div class="section-head"><h2>Qué queremos de Lucas</h2></div>${state.decisions.filter(x=>x.meetingId===m.id).map(x=>`<div class="wide-card"><span class="spark">?</span><div><b>${esc(x.question)}</b></div><span></span></div>`).join('')}</section>`}
function topicsPage(){return `<section class="app-page"><div class="simple-head"><h1>Temas</h1></div><div class="app-list">${state.topics.map(t=>`<a class="app-row" href="#topics/${t.id}"><div><strong>${esc(t.title)}</strong><span>${esc(t.latestUpdate)}</span></div><div class="row-end"><span class="mini-state ${t.status}">${esc(t.status)}</span><i>›</i></div></a>`).join('')}</div></section>`}
function topicPage(id){const t=state.topics.find(x=>x.id===id);if(!t)return missing();const ds=state.deliverables.filter(d=>d.topicId===id);return `<section class="app-page"><a class="back" href="#topics">‹ Temas</a><div class="detail-title"><div><h1>${esc(t.title)}</h1><span>${esc(t.latestUpdate)}</span></div></div><div class="fact-strip"><div><span>Próxima acción</span><b>${esc(t.nextAction)}</b></div><div><span>Need from Lucas</span><b>${esc(t.needFromLucas||'—')}</b></div></div><div class="section-head"><h2>Entregables relacionados</h2></div>${listDeliverables(ds)}</section>`}
function deliverablesPage(){const order=['ready-to-show','candidate','work-in-progress','shown-reviewed','archived-superseded'];const sorted=[...state.deliverables].sort((a,b)=>order.indexOf(a.maturity)-order.indexOf(b.maturity));return `<section class="app-page"><div class="simple-head"><h1>Entregables</h1></div><div class="chip-row"><span class="chip active">Todos</span><span class="chip">Listos</span><span class="chip">Candidatos</span></div>${listDeliverables(sorted)}</section>`}
function deliverablePage(id){const d=state.deliverables.find(x=>x.id===id);if(!d)return missing();const topic=state.topics.find(t=>t.id===d.topicId);return `<section class="app-page"><a class="back" href="#deliverables">‹ Entregables</a><div class="detail-title"><div><h1>${esc(d.title)}</h1><span>${typeLabel(d.type)} · ${esc(d.version)}</span></div></div><div class="state-counters"><div class="ok"><span>Madurez</span><b>${d.maturity==='ready-to-show'?'✓':'○'}</b></div><div><span>Faltan</span><b>${d.missingDependencies.length}</b></div><div><span>1:1</span><b>${esc(d.targetMeetingId.slice(5))}</b></div></div><div class="fact-strip"><div><span>Objetivo</span><b>${esc(d.objective)}</b></div><div><span>Review ask</span><b>${esc(d.reviewAsk||'—')}</b></div></div><div class="section-head"><h2>Qué falta</h2></div>${d.missingDependencies.length?`<div class="compact-list">${d.missingDependencies.map(x=>`<div class="compact-item"><i>○</i><b>${esc(x)}</b><span></span></div>`).join('')}</div>`:`<div class="done-card">No hay dependencias pendientes registradas.</div>`}${d.link?`<a class="wide-action external-link" href="${esc(d.link)}" target="_blank" rel="noreferrer">Abrir entregable</a>`:''}<div class="section-head"><h2>Tema</h2></div><a class="app-row" href="#topics/${topic.id}"><div><strong>${esc(topic.title)}</strong><span>${esc(topic.latestUpdate)}</span></div><i>›</i></a></section>`}
function historyPage(){return `<section class="app-page"><div class="simple-head"><h1>Histórico</h1></div><div class="blank">El histórico se llenará después del primer 1:1 registrado.</div></section>`}
function listDeliverables(list){return `<div class="app-list">${list.map(d=>`<a class="app-row" href="#deliverables/${d.id}"><div><strong>${esc(d.title)}</strong><span>${typeLabel(d.type)} · ${maturityLabel(d.maturity)}</span></div><div class="row-end"><span class="mini-state ${d.maturity==='ready-to-show'?'ready':'preparing'}">${maturityLabel(d.maturity)}</span><i>›</i></div></a>`).join('')}</div>`}
function missing(){return `<section class="app-page"><h1>No encontrado</h1></section>`}
function fmtDate(d){return new Intl.DateTimeFormat('es',{weekday:'long',day:'numeric',month:'long'}).format(new Date(d+'T12:00:00'))}
function render(){renderNav();const r=route();let html;if(r.page==='next')html=nextPage();else if(r.page==='topics'&&r.id)html=topicPage(r.id);else if(r.page==='topics')html=topicsPage();else if(r.page==='deliverables'&&r.id)html=deliverablePage(r.id);else if(r.page==='deliverables')html=deliverablesPage();else if(r.page==='history')html=historyPage();else html=homePage();$('#main').innerHTML=html}
window.addEventListener('hashchange',render);render();