(() => {
  const KEY='joseluis-letter-builder-v2';
  const blank=()=>({sender:{name:'Joseluis Esteban MORAGA NUÑEZ',address:'',phone:'',email:'',subtitle:''},es:{date:'',recipient:'',address:'',subject:'',opening:'Estimado Señor o Señora,',body:'',closing:'Sin nada más que agregar, espero su pronta respuesta y les envío saludos cordiales,'},fr:{date:'',recipient:'',address:'',subject:'',opening:'Madame, Monsieur,',body:'',closing:'Dans l’attente de votre réponse, je vous prie d’agréer, Madame, Monsieur, l’expression de mes salutations distinguées,'}});
  let letters=load();let lang='es';
  function load(){try{return JSON.parse(localStorage.getItem(KEY))||blank()}catch{return blank()}}
  function save(){localStorage.setItem(KEY,JSON.stringify(letters))}
  const ids=['date','recipient','address','subject','opening','body','closing'];
  const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const tex=s=>String(s??'').replace(/\\/g,'\\textbackslash{}').replace(/([#$%&_{}])/g,'\\$1').replace(/\^/g,'\\textasciicircum{}').replace(/~/g,'\\textasciitilde{}');
  function fill(){const d=letters[lang]||{};ids.forEach(id=>document.querySelector('#'+id).value=d[id]||'');render()}
  ids.forEach(id=>document.querySelector('#'+id).oninput=e=>{letters[lang][id]=e.target.value;save();render()});
  document.querySelector('#lang').onchange=e=>{lang=e.target.value;fill()};
  document.querySelector('#import').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);const next=blank();if(data.cv?.basics){const b=data.cv.basics;next.sender={name:b.name||next.sender.name,address:b.location?.address||'',phone:b.phone||'',email:b.email||'',subtitle:''}}if(data.letters)Object.assign(next,{es:data.letters.es||next.es,fr:data.letters.fr||next.fr});else if(data.es||data.fr)Object.assign(next,{es:data.es||next.es,fr:data.fr||next.fr});letters=next;save();fill()}catch{alert('Archivo de importación no válido')}};r.readAsText(f)};
  function paras(text){return h(text).split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${x.replace(/\n/g,'<br>')}</p>`).join('')}
  function render(){const d=letters[lang],s=letters.sender||blank().sender,subjectPrefix=lang==='fr'?'Objet :':'Asunto:';document.querySelector('#preview').innerHTML=`<div class="sender"><strong>${h(s.name)}</strong>${s.address?`<span>${h(s.address)}</span>`:''}${s.phone?`<span>✎ ${h(s.phone)}</span>`:''}${s.email?`<span>✉ ${h(s.email)}</span>`:''}</div><div class="date">${h(d.date)}</div><div class="recipient"><strong>${h(d.recipient)}</strong>${d.address?`<span>${h(d.address)}</span>`:''}</div>${d.subject?`<div class="subject"><span>${subjectPrefix}</span> ${h(d.subject)}</div>`:''}<div class="opening">${h(d.opening)}</div><div class="body">${paras(d.body)}</div><div class="closing">${h(d.closing)}</div><div class="signature"><strong>${h(s.name)}</strong>${s.subtitle?`<span>${h(s.subtitle)}</span>`:''}</div>`}
  function latex(){const d=letters[lang],s=letters.sender||blank().sender,prefix=lang==='fr'?'Objet :':'Asunto:';return `\\documentclass[11pt,a4paper]{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage[a4paper,top=1.7cm,bottom=1.7cm,left=2.0cm,right=2.0cm]{geometry}\n\\usepackage{ragged2e}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0pt}\n\\begin{document}\n\\begin{flushright}\n\\textbf{${tex(s.name)}}\\\\\n${tex(s.address).replace(/\n/g,'\\\\\n')}\\\\\n${tex(s.phone)}\\\\\n${tex(s.email)}\n\\end{flushright}\n\\vspace{1.2em}\n\\begin{flushright}${tex(d.date)}\\end{flushright}\n\\vspace{0.5em}\n\\textbf{${tex(d.recipient)}}\\\\\n${tex(d.address).replace(/\n/g,'\\\\\n')}\n\\vspace{4.5em}\n\\textbf{${prefix}} ${tex(d.subject)}\n\\vspace{2.2em}\n${tex(d.opening)}\n\\vspace{1.4em}\n\\justifying\n${tex(d.body).replace(/\n\n/g,'\\par\\vspace{0.7em}\n').replace(/\n/g,' ')}\n\\vspace{0.9em}\n\\begin{center}${tex(d.closing)}\\end{center}\n\\vspace{2.2em}\n\\begin{flushright}\\textbf{${tex(s.name)}}${s.subtitle?`\\\\${tex(s.subtitle)}`:''}\\end{flushright}\n\\end{document}`}
  const dl=(n,t)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/plain'}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
  document.querySelector('#tex').onclick=()=>dl(`Carta_${lang.toUpperCase()}.tex`,latex());document.querySelector('#pdf').onclick=()=>window.print();fill();
})();